"""A missing, stale, or malformed lock feed never means zero live locks."""
import os
import tempfile
import unittest
from datetime import datetime, timedelta
from pathlib import Path
from unittest.mock import patch

from gui.api import unified_api


HEADER = "<!-- AUTO-GENERATED by lock_scan.py --write-cache. DO NOT edit manually. -->"


class OceanGovernanceFeedTest(unittest.TestCase):
    def test_feed_fresh_stale_and_missing(self):
        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "LOCK-CACHE.md"
            with patch.dict(os.environ, {"BACH_LOCK_CACHE": str(cache)}):
                self.assertIsNone(unified_api._lock_cache_snapshot()["count"])
                stamp = datetime.now().astimezone().isoformat(timespec="seconds")
                cache.write_text(
                    f"{HEADER}\nAs of: {stamp}\nActive locks: 1\n"
                    "| Path | scope | owner | created | remaining |\n"
                    "|---|---|---|---|---|\n"
                    "| C:\\private\\LOCK.user.txt | user | private owner | today | ? |\n",
                    encoding="utf-8",
                )
                fresh = unified_api._lock_cache_snapshot()
                self.assertEqual(fresh["availability"], "available")
                self.assertEqual(fresh["count"], 1)
                self.assertEqual(fresh["locks"][0]["name"], "LOCK.user.txt")
                self.assertNotIn("private owner", str(fresh))
                stale_stamp = (datetime.now().astimezone() - timedelta(hours=2)).isoformat(timespec="seconds")
                cache.write_text(cache.read_text(encoding="utf-8").replace(stamp, stale_stamp), encoding="utf-8")
                stale = unified_api._lock_cache_snapshot()
                self.assertEqual(stale["availability"], "stale")
                self.assertIsNone(stale["count"])
                cache.write_text("invalid", encoding="utf-8")
                self.assertEqual(unified_api._lock_cache_snapshot()["error"], "lock_cache_invalid")


if __name__ == "__main__":
    unittest.main()
